name: Project Release
on: [push]
env:
  VERSION: 0.1.1659118143
jobs:
  release:
    name: Build MD5 Endpoint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Enpoint
      run: |
        file=src/main.cpp
        [[ -f "$file" ]] || exit 127
        main_cpp_md5_text='{\n\t"schemaVersion": 1,\n\t"color": "ffff99",\n\t"label": "MAIN CPP MD5",\n\t"message": "PLACEHOLDER",\n\t"labelColor": "1d1d1d",\n\t"style": "for-the-badge",\n\t"namedLogo": "cpp"\n}'
        if ! [[ -d "docs/json" ]]; then
          mkdir -p docs/json || exit 126
        fi
        if ! [[ -f "docs/json/main_cpp_md5.json" ]]; then
          touch "docs/json/main_cpp_md5.json" || exit 125
        fi
        echo -e "$main_cpp_md5_text" > "docs/json/main_cpp_md5.json"
        sed -i "s/\"message\": \".*\"/\"message\": \"$(md5sum $file | cut -d' ' -f 1)\"/g" "docs/json/main_cpp_md5.json"
        git tag -l [0-9]*
        git add docs/json/*
        git config --global user.name 'Lateralus138'
        git config --global user.email 'Lateralus138@users.noreply.github.com'
        git commit --allow-empty -am "Pushed $(printf '%s ' docs/json/*) of $(git tag -l [0-9].*) to master.  - $(date -u)"
        git push --force origin master
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        tag: ${VERSION}
        name: Beta - ${VERSION}
        bodyFile: docs/md/release.md
        prerelease: True
        artifacts: src/main.cpp
        token: ${{ secrets.GITHUB_TOKEN }}